"""add staff invitations

Revision ID: f0f9b1bb32f3
Revises: 7a775030b671
Create Date: 2026-09-25 15:47:14.458548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f9b1bb32f3'
down_revision: Union[str, Sequence[str], None] = '7a775030b671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_invitations_email'), 'staff_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_staff_invitations_id'), 'staff_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_staff_invitations_invited_by_user_id'), 'staff_invitations', ['invited_by_user_id'], unique=False)
    op.create_index(op.f('ix_staff_invitations_restaurant_id'), 'staff_invitations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_staff_invitations_token_hash'), 'staff_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_invitations_token_hash'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_restaurant_id'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_invited_by_user_id'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_id'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_email'), table_name='staff_invitations')
    op.drop_table('staff_invitations')
    # ### end Alembic commands ###
